/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPrincipal;
import java.awt.Color;

/**
 *
 * @author pablo
 */
public class HistoriaGUI extends javax.swing.JFrame {

    /**
     * Creates new form HistoriaGUI
     */
    public HistoriaGUI(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
        
        setLocationRelativeTo(null);
        setBackground((new Color(0, 0, 0, 0)));
    }
    
    
     public void escuchar(ControladorPrincipal controlador)
     {
         btnVolverHistoria.setActionCommand("btnVolverHistoria");
        
         btnVolverHistoria.addActionListener(controlador);

       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolverHistoria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonVolver.png"))); // NOI18N
        btnVolverHistoria.setBorderPainted(false);
        btnVolverHistoria.setContentAreaFilled(false);
        getContentPane().add(btnVolverHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 760, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuHistoria.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverHistoria;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
