/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPrincipal;

/**
 *
 * @author pablo
 */
public class InstruccionesGUI extends javax.swing.JFrame {

    /**
     * Creates new form InstruccionesGUIU
     */
    public InstruccionesGUI(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
        
        setLocationRelativeTo(null);
    }
    
      public void escuchar(ControladorPrincipal controlador)
     {
         btnVolverInstrucciones.setActionCommand("btnVolverInstrucciones");
       
         btnVolverInstrucciones.addActionListener(controlador);

       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolverInstrucciones = new javax.swing.JButton();
        jlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1270, 1061));
        setSize(new java.awt.Dimension(1270, 1061));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonVolver.png"))); // NOI18N
        btnVolverInstrucciones.setBorderPainted(false);
        btnVolverInstrucciones.setContentAreaFilled(false);
        getContentPane().add(btnVolverInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 770, -1, -1));

        jlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuInstrucciones.png"))); // NOI18N
        jlabel.setText("jLabel1");
        getContentPane().add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverInstrucciones;
    private javax.swing.JLabel jlabel;
    // End of variables declaration//GEN-END:variables
}
