/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPrincipal;

/**
 *
 * @author pablo
 */
public class JuegoGUI extends javax.swing.JFrame {


    
    public JuegoGUI(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }
    
   public void escuchar(ControladorPrincipal controlador)
     {
         btnPausa.setActionCommand("btnPausa");
        
         btnPausa.addActionListener(controlador);

       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPausa = new javax.swing.JButton();
        panelJuego1 = new vista.PanelJuego();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonMenu.png"))); // NOI18N
        btnPausa.setBorderPainted(false);
        btnPausa.setContentAreaFilled(false);
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, -1, -1));

        javax.swing.GroupLayout panelJuego1Layout = new javax.swing.GroupLayout(panelJuego1);
        panelJuego1.setLayout(panelJuego1Layout);
        panelJuego1Layout.setHorizontalGroup(
            panelJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        panelJuego1Layout.setVerticalGroup(
            panelJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(panelJuego1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 600, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Laberinto.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
     
    }//GEN-LAST:event_btnPausaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPausa;
    private javax.swing.JLabel jLabel1;
    private vista.PanelJuego panelJuego1;
    // End of variables declaration//GEN-END:variables
}
