/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPrincipal;

/**
 *
 * @author pablo
 */
public class MainMenuGUI extends javax.swing.JFrame {

     private InstruccionesGUI instruccionesGUI;
     
    public MainMenuGUI( ControladorPrincipal controlador) {
         initComponents();
         escuchar(controlador);
         setVisible(true);
    }
    
     public void escuchar(ControladorPrincipal controlador){
         
         btnInstrucciones.setActionCommand("btnInstrucciones");
         btnJugar.setActionCommand("btnJugar");
         btnSalir.setActionCommand("btnSalir");
         btnHistoria.setActionCommand("btnHistoria");
        
              btnInstrucciones.addActionListener(controlador);
              btnJugar.addActionListener( controlador);
              btnSalir.addActionListener( controlador);
              btnHistoria.addActionListener( controlador);
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonSalir.png"))); // NOI18N
        btnSalir.setText("jButton1");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 850, 420, 140));

        btnJugar.setBackground(new java.awt.Color(0, 0, 0));
        btnJugar.setForeground(new java.awt.Color(0, 0, 0));
        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonJuego.png"))); // NOI18N
        btnJugar.setText("jButton1");
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 430, 140));

        btnHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonHistoria.png"))); // NOI18N
        btnHistoria.setText("jButton1");
        btnHistoria.setBorder(null);
        btnHistoria.setContentAreaFilled(false);
        getContentPane().add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 430, 140));

        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonInstrucciones.png"))); // NOI18N
        btnInstrucciones.setText("jButton1");
        btnInstrucciones.setBorderPainted(false);
        btnInstrucciones.setContentAreaFilled(false);
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 420, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MainMenuLaberinto.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
