/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPrincipal;

/**
 *
 * @author pablo
 */
public class MenuPausaGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuPausaGUI
     */
    public MenuPausaGUI(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
        
        setLocationRelativeTo(null);
    }
      public void escuchar(ControladorPrincipal controlador)
     {
         btnReanudar.setActionCommand("btnReanudar");
         btnVolverAlMenu.setActionCommand("btnVolverAlMenu");
        
         btnReanudar.addActionListener(controlador);
         btnVolverAlMenu.addActionListener(controlador);

       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReanudar = new javax.swing.JButton();
        btnVolverAlMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReanudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonReanudar.png"))); // NOI18N
        btnReanudar.setBorderPainted(false);
        btnReanudar.setContentAreaFilled(false);
        getContentPane().add(btnReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        btnVolverAlMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SalirAlMenuPausa.png"))); // NOI18N
        btnVolverAlMenu.setBorderPainted(false);
        btnVolverAlMenu.setContentAreaFilled(false);
        getContentPane().add(btnVolverAlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuPausa.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReanudar;
    private javax.swing.JButton btnVolverAlMenu;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
