/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPrincipal;
import java.awt.Color;

/**
 *
 * @author pablo
 */
public class SalirGUI extends javax.swing.JFrame {

    /**
     * Creates new form SalirGUI
     */
    public SalirGUI(ControladorPrincipal controlador) {
        setUndecorated(true); 
        setBackground(new Color(0, 0, 0, 0)); 
        
        initComponents();
        escuchar(controlador);
        setLocationRelativeTo(null);

        
        setLocationRelativeTo(null); 
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
      public void escuchar(ControladorPrincipal controlador)
     {
         btnSi.setActionCommand("btnSi");
         btnSi.addActionListener(controlador);
         
         btnNo.setActionCommand("btnNo");
         btnNo.addActionListener(controlador);
       }
      
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNo = new javax.swing.JButton();
        btnSi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonNo.png"))); // NOI18N
        btnNo.setBorderPainted(false);
        btnNo.setContentAreaFilled(false);
        getContentPane().add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 780, -1, -1));

        btnSi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonSí.png"))); // NOI18N
        btnSi.setBorderPainted(false);
        btnSi.setContentAreaFilled(false);
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });
        getContentPane().add(btnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 760, -1, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuSalir.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
