/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorLaberinto;
import java.awt.Color;

/**
 *
 * @author pablo
 */
public class VictoriaGUI extends javax.swing.JFrame {

    /**
     * Creates new form VictoriaGUI
     */
   public VictoriaGUI(ControladorLaberinto controlador) 
    {
        setUndecorated(true); 
        setBackground(new Color(0, 0, 0, 0));
        
        initComponents();
        escuchar(controlador);
        
        setLocationRelativeTo(null);

        // Ajustar propiedades del JFrame
        setLocationRelativeTo(null); 
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public void escuchar(ControladorLaberinto controlador)
    { 
        btnReintentarVictoria.setActionCommand("btnReintentarVictoria");
        btnReintentarVictoria.addActionListener(controlador);
         
        btnVolverAlMenuVictoria.setActionCommand("btnVolverAlMenuVictoria");
        btnVolverAlMenuVictoria.addActionListener(controlador);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolverAlMenuVictoria = new javax.swing.JButton();
        btnReintentarVictoria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverAlMenuVictoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonVolverMenu.png"))); // NOI18N
        btnVolverAlMenuVictoria.setBorderPainted(false);
        btnVolverAlMenuVictoria.setContentAreaFilled(false);
        getContentPane().add(btnVolverAlMenuVictoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 640, -1, -1));

        btnReintentarVictoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonReintentar.png"))); // NOI18N
        btnReintentarVictoria.setBorderPainted(false);
        btnReintentarVictoria.setContentAreaFilled(false);
        getContentPane().add(btnReintentarVictoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PantallaVictoria.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReintentarVictoria;
    private javax.swing.JButton btnVolverAlMenuVictoria;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
